# Generated by Django 2.1.2 on 2019-01-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jedzonkorecipe',
            name='instruction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
